export const FORM_PROJECT ='FORM_PROJECT'
export const OBTAIN_PROJECT ='OBTAIN_PROJECT'
export const ADD_PROJECT ='ADD_PROJECT'
export const VALIDATE_FORM ='VALIDATE_FORM'
export const ACTUAL_PROJECT ='ACTUAL_PROJECT'
export const DELETE_PROJECT ='DELETE_PROJECT'
export const PROJECT_ERROR = 'PROJECT_ERROR'

export const TASKS_PROJECT = 'TASKS_PROJECT'
export const ADD_TASK = 'ADD_TASK'
export const VALIDATE_TASK = 'VALIDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const ACTUAL_TASK = 'ACTUAL_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const CLEAR_TASK = 'CLEAR_TASK'

export const SHOW_ALERT = 'SHOW_ALERT'
export const CLOSE_ALERT = 'CLOSE_ALERT'

export const REGISTRY_SUCCESSFUL = 'REGISTRY_SUCCESSFUL'
export const REGISTRY_ERROR = 'REGISTRY_ERROR'
export const OBTAIN_USER = 'OBTAIN_USER'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CLOSE_SESSION = 'CLOSE_SESSION'


